#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Oct 15, 2025 07:56:46 AM %z  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m61 -background #263d79 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 681x688+416+23
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m61" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Segoe UI} -size 9" -tearoff 0 
    ttk::label "$top.tLa52" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Small Fonts} -size 18" -relief raised \
        -text "                                                welcome !" \
        -compound left 
    vTcl:DefineAlias "$top.tLa52" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$top.tLa53" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Small Fonts} -size 12" -relief flat \
        -text "                                                                     NAMIRA'S STORE" \
        -compound left 
    vTcl:DefineAlias "$top.tLa53" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can56" \
        -background #d9eff4 -borderwidth 2 -closeenough 1.0 -height 458 \
        -highlightbackground #d9d9d9 -highlightcolor #b8bdfa \
        -insertbackground #000000 -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 559 
    vTcl:DefineAlias "$top.can56" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can56
    ttk::label "$site_3_0.tLa48" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Sitka Display} -size 12 -weight bold" -relief flat \
        -text "  Nama Barang" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa48" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa54" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Sitka Display} -size 12 -weight bold" -relief flat \
        -text "  Harga Barang" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa54" "TLabel3_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa58" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Sitka Display} -size 12 -weight bold" -relief flat \
        -text "        Jumlah" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa58" "TLabel3_1_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa64" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Sitka Display} -size 12 -weight bold" -relief flat \
        -text "        Uang" -compound left 
    vTcl:DefineAlias "$site_3_0.tLa64" "TLabel3_1_1_1" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but62" \
        -activebackground #4497fd -activeforeground #9795ac \
        -background #b7f0f7 -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI Semibold} -size 11 -weight bold" \
        -foreground #d0c6f9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Hitung" 
    vTcl:DefineAlias "$site_3_0.but62" "Hitung" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa68" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Segoe UI Historic} -size 12" -relief flat -text "Rp" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa68" "TLabel4_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn65" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn65" "TEntry4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa63" \
        -background #ffffbf -foreground #d0c6f9 \
        -font "-family {Segoe UI Historic} -size 12" -relief flat -text "Rp" \
        -compound left 
    vTcl:DefineAlias "$site_3_0.tLa63" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn59" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn59" "TEntry3" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but67" \
        -activebackground #4497fd -activeforeground #9795ac \
        -background #b7f0f7 -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI Semibold} -size 11 -weight bold" \
        -foreground #d0c6f9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Kembalian" 
    vTcl:DefineAlias "$site_3_0.but67" "Hitung_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn49" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn49" "TEntry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn56" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam 
    vTcl:DefineAlias "$site_3_0.tEn56" "TEntry2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tLa48 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.067 -width 0 \
        -relwidth 0.204 -height 0 -relheight 0.06 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.179 -width 0 \
        -relwidth 0.204 -height 0 -relheight 0.06 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa58 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.29 -width 0 \
        -relwidth 0.204 -height 0 -relheight 0.06 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa64 \
        -in $site_3_0 -x 0 -relx 0.054 -y 0 -rely 0.603 -width 0 \
        -relwidth 0.204 -height 0 -relheight 0.06 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 0 -relx 0.072 -y 0 -rely 0.402 -width 87 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa68 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.714 -width 0 \
        -relwidth 0.633 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn65 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.58 -width 356 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa63 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.402 -width 0 \
        -relwidth 0.633 -height 0 -relheight 0.083 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn59 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.29 -width 356 -relwidth 0 \
        -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 0 -relx 0.072 -y 0 -rely 0.714 -width 87 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn49 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.067 -width 356 \
        -relwidth 0 -height 31 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn56 \
        -in $site_3_0 -x 0 -relx 0.304 -y 0 -rely 0.179 -width 356 \
        -relwidth 0 -height 31 -relheight 0 -anchor nw -bordermode ignore 
    button "$top.but73" \
        -activebackground #4497fd -activeforeground #9795ac \
        -background #b7f0f7 -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI Semibold} -size 11 -weight bold" \
        -foreground #d0c6f9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Keluar" 
    vTcl:DefineAlias "$top.but73" "Hitung_1_1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa52 \
        -in $top -x 0 -y 0 -rely -0.029 -width 0 -relwidth 1.023 -height 0 \
        -relheight 0.135 -anchor nw -bordermode ignore 
    place $top.tLa53 \
        -in $top -x 0 -relx -0.015 -y 0 -rely 0.058 -width 0 -relwidth 1.04 \
        -height 0 -relheight 0.06 -anchor nw -bordermode ignore 
    place $top.can56 \
        -in $top -x 0 -relx 0.088 -y 0 -rely 0.218 -width 0 -relwidth 0.821 \
        -height 0 -relheight 0.666 -anchor nw -bordermode ignore 
    place $top.but73 \
        -in $top -x 0 -relx 0.778 -y 0 -rely 0.901 -width 87 -relwidth 0 \
        -height 36 -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

